rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
  no-console: 0  

env:
  es6: true
  node: true

globals:
  module: false
  require: false
  console: false

extends: eslint:recommended
parser: babel-eslint
